Change SSE response structure so that it's compatible with GraphQL SSE standard
absinthe-graphql/absinthe_plug pull request #292
Opened 2024-07-29 20:40 UTC by perzanko

The current payload of a subscription response in the SSE protocol looks like this.

```
xxx
```
It is simply encoded JSON.

The proposed change (breaking change!) is as follows:
```
```
The encoded JSON is wrapped in a standardized structure consistent with [GraphQL over Server-Sent Events Protocol specification](https://github.com/enisdenjo/graphql-sse/blob/master/PROTOCOL.md#next-event).

Reason:
Many graphql clients expect a response consistent with the above standard. An example of this is [graphql-mesh](https://the-guild.dev/graphql/mesh/v1/serve/features/subscriptions#example), which expects responses from subgraph services sent in a structured manner. Or even the highly popular client [graphql-sse](https://www.npmjs.com/package/@graphql-sse/client) used in browsers also requires this format.

 Please note:
This is a breaking change and should be implemented with backward compatibility. Perhaps introducing an additional configuration option or an option to override the response format would be appropriate in this case, perhaps even more appropriate.

2024-07-29 21:04 UTC, perzanko commented
@benwilson512 😉☝️

2024-07-30 13:20 UTC, benwilson512 requested changes
Hey @perzanko thanks for the PR!

As you note, this is a backwards incompatible change. I think we should support some sort of flag on probably the `Absinthe.Plug` plug that we can use to switch between the types of return shapes.

2024-12-10 13:36 UTC, fladens commented
@benwilson512 are you planning on fixing this still, or should I take over to add this flag?
It doesn't really work for me else for my current setup.

Here for anyone who comes across this and needs a bit ugly but working workaround.
(I am also using a custom AbsinthePubsub for SSE)

```elixir
plug Absinthe.Plug,
  schema: GuestgoodieApiWeb.Graphql.AdminSchema,
  pubsub: GuestgoodieApiWeb.Graphql.AbsinthePubsub,
  json_codec: __MODULE__

@doc false
def encode!(%{sub: data}, config) do
  "event: next\ndata: #{Jason.encode!(data, config)}"
end

@doc false
def encode!(value, config) do
  Jason.encode!(value, config)
end
```

and

```elixir
def publish_subscription(topic, result) do
  broadcast = %{
    topic: topic,
    event: "subscription:data",
    payload: %{
      result: %{sub: result},
      subscriptionId: topic
    }
  }

  Phoenix.PubSub.local_broadcast(@pubsub, topic, broadcast)
end
```

2024-12-29 01:33 UTC, emancu commented
@benwilson512  (cc @perzanko ) I updated the PR with a few fixes that we need in production (fixing also https://github.com/absinthe-graphql/absinthe_plug/issues/294)

1st commit -> Fixes the match with `:closed`, making it less restrictive.
2nd commit -> Adding `standard_sse` flag, to make the changes backwards compatible 💪 
3rd commit -> Tinny typo (IMO) but could be a breaking change. I'm happy to drop that commit if you want.

🙏 Sorry we didn't update the PR before, I just discovered this fork on Monday!

2024-12-29 01:41 UTC, emancu commented on lib/absinthe/plug.ex
> +  defp subscribe_loop(conn, topic, config) do
⚠️ This is the _only_ breaking change. I can easily undo it.

2024-12-29 11:47 UTC, emancu commented on lib/absinthe/plug.ex
> +          {:error, _} ->
ℹ️ Source code [chunk/2](https://github.com/elixir-plug/plug/blob/003a7adb3a104b9aa6cb76f242e7b1c0480cf4db/lib/plug/conn.ex#L566)

2025-01-24 19:05 UTC, merged